config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('pages.urls')),
    path('', RedirectView.as_view(url='/pages')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    # path('contact/', views.contact, name='contact'),
    # path('<str:city>/', views.datasets, name='sets'),
]

pages/models.py
from django.db import models
# from django.template.defaultfilters import slugify

# class Location(models.Model):
#     city = models.CharField(max_length=50)
#     state = models.CharField(max_length=50)
#     abbr = models.CharField(max_length=2)
#     image = models.ImageField(null=True, blank=True)

#     def __str__(self):
#         return self.city
    
#     @property
#     def imageURL(self):
#         try:
#             url = self.image.url
#         except:
#             url = ''
#         return url

# class Dataset(models.Model):
#     PLATFORM = (
#         ('0', 'Twitter'),
#         ('1', 'Instagram'),
#         ('2', 'LinkedIn'),   
#     )
#     title = models.CharField(max_length=50)
#     rows = models.IntegerField(null=True, blank=True, default=1)
#     slug = models.SlugField(null=False)
#     location = models.ForeignKey(Location, on_delete=models.PROTECT)
#     category = models.CharField(max_length=22, choices=PLATFORM, default=0, blank=True, null=True)

#     def __str__(self):
#         return self.title

#     def save(self, *args, **kwargs):
#         if not self.slug:
#             self.slug = slugify(self.title)
#         return super().save(*args, **kwargs)

# class Contact(models.Model):
#     first = models.CharField(max_length=28)
#     last = models.CharField(max_length=28)
#     message = models.TextField(null=True, blank=True)
#     form_date = models.DateTimeField(auto_now_add=True)
    
#     class Meta:
#         ordering = ['-form_date']

#     def __str__(self):
#         return self.last

pages/views.py
from django.shortcuts import render, redirect
# from .models import Location, Dataset, Contact
# from .forms import ContactForm
# from django.contrib import messages


def index(request):
    # locations = Location.objects.all()
    # context = {'locations': locations}
    return render(request, 'pages/index.html')


# def datasets(request, city):
#     location = Location.objects.get(city=city)
#     datasets = location.dataset_set.all()
#     return render(request, 'datasets/sets.html', {'datasets': datasets, 'location': location})


# def contact(request):
#     if request.method != 'POST':
#         form = ContactForm()
#     else:
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             form.save()
#             messages.success(request, 'Your contact info has been successfully submitted.')
#             return redirect ('datasets:index')
#     context = {'form': form}
#     return render(request, 'datasets/contact.html', context)

pages/templates/pages/base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}

  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta
      name="author"
      content="Laney, R. Brendan (web-developer & engineer)"
    />

    <!-- UIkit CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/uikit@3.8.0/dist/css/uikit.min.css"
    />

    <!-- Custom stylesheet -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

    <title>Django-app</title>
    <link rel="shortcut icon" type="image/png" href="#" />
  </head>

  <body>
    <!-- Navbar - top of page -->
    <nav class="uk-navbar-container" uk-navbar>
      <div class="uk-navbar-left">
        <span
          id="brand"
          class="uk-icon uk-margin-left uk-text-emphasis"
          uk-icon="icon: play-circle; ratio: 1.5"
        ></span>
        <a
          id="brand"
          class="uk-navbar-item uk-logo uk-text-bold uk-text-emphasis"
          href="{% url 'pages:index' %}"
        >
          Home
        </a>
      </div>
      <div class="uk-navbar-right">
        <ul id="element" class="uk-navbar-nav">
          <li class="uk-active">
            <a
              class="uk-icon uk-margin-small-right"
              href="{% url 'pages:index' %}"
              uk-icon="home"
            ></a>
          </li>
          <li class="uk-*">
            <a
              class="uk-icon uk-margin-small-right"
              href="#"              
              uk-icon="mail"
            ></a>
          </li>
          <li class="uk-*">
            <a
              class="uk-icon uk-margin-small-right"
              href="#"
              uk-icon="info"
            ></a>
          </li>
        </ul>
      </div>
    </nav>
    <!-- End navbar -->

    <!-- Site header -->
    <div class="uk-flex uk-flex-center">
      <div>{% block title %}{% endblock %}</div>
    </div>
    <!-- End header -->

    <!-- Main div content -->
    <div id="main" class="uk-container uk-container-large">
      <!-- Define region for cascading templates that inherit this html -->
      {% block content %}{% endblock %}
    </div>

    <!-- UIkit JS -->
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.8.0/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.8.0/dist/js/uikit-icons.min.js"></script>
  </body>
</html>

pages/templates/pages/index.html
{% extends 'pages/base.html' %}
{% load static %}

{% block title %}
  <h1 class="uk-heading-large">Django & UiKit</h1>
  <h3 class="uk-heading-line uk-text-center">
    <span>A sample web application</span>
  </h3>
{% endblock %}

{% block content %}
<div class="uk-flex uk-flex-center">
  {% for location in locations %}
    <div id="index-card" class="uk-card uk-card-hover">
      <div class="uk-card-header">
        Stuff goes here
        <!-- <h2 class="uk-card-title">{{ location.city }}, {{location.state}}</h2> -->
      </div>
      <div class="uk-card-footer">
        Link goes here
      </div>
    </div>
  {% endfor %}
</div>
{% endblock %}